# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-symlinks
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args:
        -   --ignore-missing-imports
        -   --disallow-incomplete-defs
        -   --disallow-untyped-defs
        -   --check-untyped-defs
        -   --no-implicit-optional
-   repo: https://github.com/PyCQA/doc8
    rev: 0.8.1
    hooks:
    -   id: doc8
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
    -   id: isort
